### ISSUE TITLE
ml5 is not defined

### ISSUE THREAD

**Issue by nitin-bommi** [PranavBharadwaj-1328/Gait-Analysis#2]
As i have run the code, i find that ml5 file is not properly incorporated ot added as reference to the sketch file.

**Comment by AnuragAnalog** [comment]
It's doesn't work in chrome, try running it in Firefox!

**Comment by PranavBharadwaj-1328** [comment]
> As i have run the code, i find that ml5 file is not properly incorporated ot added as reference to the sketch file.

It works perfectly now  in any browser and it also shows the diatance between your feet in pixels
